language: csharp
solution: SafetyFirst.sln
install:
  - nuget restore SafetyFirst.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release SafetyFirst.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./SafetyFirst.Specs/bin/Release/net461/SafetyFirst.Specs.dll